name: Good First Issues

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run Linters
        run: |
          pip install isort flake8 black
          make lint

